In [0]:
import numpy as np


In [0]:
import numpy as np

In [0]:
A = np.array([
              [2, 0, 6,],
              [-1, 5, -4,],
              [3, -5, 2],
             ])

In [0]:
X = np.array([[4],[3],[2]])

In [0]:
X


array([[4],
       [3],
       [2]])

In [0]:
Ai = np.linalg.inv(A)

In [0]:
print(Ai)

[[ 0.125  0.375  0.375]
 [ 0.125  0.175 -0.025]
 [ 0.125 -0.125 -0.125]]


In [0]:
print(np.linalg.inv(A))

[[ 0.125  0.375  0.375]
 [ 0.125  0.175 -0.025]
 [ 0.125 -0.125 -0.125]]


In [0]:
np.dot(A,Ai)

array([[ 1.00000000e+00,  8.32667268e-17,  8.32667268e-17],
       [ 0.00000000e+00,  1.00000000e+00, -5.55111512e-17],
       [ 0.00000000e+00, -5.55111512e-17,  1.00000000e+00]])

In [0]:
A

array([[ 2,  0,  6],
       [-1,  5, -4],
       [ 3, -5,  2]])

In [0]:
Ai

array([[ 0.125,  0.375,  0.375],
       [ 0.125,  0.175, -0.025],
       [ 0.125, -0.125, -0.125]])

In [0]:
np.dot(Ai,A)

array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  1.00000000e+00, -5.55111512e-17],
       [ 4.16333634e-17,  4.16333634e-17,  1.00000000e+00]])

In [0]:
np.multiply(A, Ai)

array([[ 0.25 ,  0.   ,  2.25 ],
       [-0.125,  0.875,  0.1  ],
       [ 0.375,  0.625, -0.25 ]])

In [0]:
  A= [[1,2],
      [3,4]]

In [0]:
B= [[2,3],
    [4,5]]

In [0]:
A= np.array(A,dtype=int)
B= np.array(B,dtype=int)

In [0]:
A*B

array([[ 2,  6],
       [12, 20]])

In [0]:
np.multiply(A,B)

array([[ 2,  6],
       [12, 20]])

In [0]:
i = np.linalg.inv(A)


In [0]:
i

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [0]:
I = np.dot(A,i)

In [0]:
I

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

In [0]:
I.astype(int)

array([[1, 0],
       [0, 0]])

In [0]:
I[1,1]

0.9999999999999996

In [0]:
[0]*3

[0, 0, 0]

In [0]:
for i in  range(3,2):
  print(i)

In [0]:
list(range(3,2))

[]

In [0]:
2-(-1*-4/3)

0.6666666666666667

In [0]:
import numpy as np


A = np.matrix([[1,1,-1],[0,1,3],[0,0,-6]])
b = np.array([9,3,8],dtype=float)


def back_sub(A,b):
    n = len(A)
    print('n is:', n)
    x = [0]*n
    for i in range(n-1,-1,-1): #this refers to the rows; i goes 2,1,0
        for j in range(i+1,n): #j goes 1,2 @ i = 0
                               #j goes 2   @ i = 1
            b[i] = b[i] - A[i,j]*x[j]
        x[i] = b[i]/A[i,i]

    return x

In [0]:
back_sub(A,b)

n is: 3


[0.6666666666666667, 7.0, -1.3333333333333333]

-1.3333333333333333

In [0]:
b = np.array([9,3,8],dtype=float)

In [0]:
b

array([9., 3., 8.])

In [0]:
b.dtype

dtype('float64')

In [0]:
x = np.arange(1,10).reshape(3,3)

In [0]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [0]:
y = np.array([1,2,3])

In [0]:
z = np.zeros_like(y)

In [0]:
z

array([0, 0, 0])

In [0]:
1. / A[-1, -1] * b[-1]

-1.3333333333333333

In [0]:
  trx5