In [0]:
import numpy as np


In [0]:
matA = np.array([
                [4, -1, 1],
                [4, -8, 1],
                [-2, 1 , 5],
])

In [0]:
matB = np.array(
                [7, -21, 15],
)

In [0]:
n = len(matB)

In [0]:
n

3

In [0]:
x = np.zeros_like(matB)

In [0]:
x

array([[0, 0, 0]])

In [0]:
iterations = int(input("Enter no of iterations: "))
tol = float(input("Enter tolerance: "))
tol = 10**tol

Enter no of iterations: 10
Enter tolerance: -3


In [69]:
X = np.zeros(n)
for k in range(0,iterations):
 for i in range(0,n):
   X[i] = (1/(matA[i,i]))*(matB[i]-(matA[1,i-1]+matA[i, (i+1):n])*(X[1,i-1]+X[i, (i+1):n]))


SyntaxError: ignored

In [0]:
X

array([ 1.,  4., -8.])

In [0]:
def jacobi(matA, matB, iguess, tol, iterations):
  n = int(input("Enter no. of variables: "))
  for x in range(n):
    for y in range(n):
      i = float(input("Enter value: "))
      matA = np.zeros((n,n))
      matA[x][y] = i

In [0]:
D = np.diag(matA)

In [0]:
D

array([ 4, -8,  5])

In [0]:
import numpy as np
from scipy.linalg import solve

def jacobi(A, b, x, n):

    D = np.diag(A)
    R = A - np.diagflat(D)
    p = np.zeros(3)
    for i in range(n):
        x = (b - R.dot(x))/ D
        print(x)
        err = np.abs(np.linalg.norm(x-p))
        if err<tol:
          break
        p=x


A = np.array([
                [4, -1, 1],
                [4, -8, 1],
                [-2, 1 , 5],
])

b = np.array(
                [7, -21, 15],
)
n = len(matB)
x = np.ones(n)
n = 25
tol = float(input("Enter tolerance: "))
tol = 10**tol


jacobi(A, b, x, n)

Enter tolerance: -9
[1.75 3.25 3.2 ]
[1.7625 3.9    3.05  ]
[1.9625 3.8875 2.925 ]
[1.990625 3.971875 3.0075  ]
[1.99109375 3.99625    3.001875  ]
[1.99859375 3.99578125 2.9971875 ]
[1.99964844 3.99894531 3.00028125]
[1.99966602 3.99985937 3.00007031]
[1.99994727 3.9998418  2.99989453]
[1.99998682 3.99996045 3.00001055]
[1.99998748 3.99999473 3.00000264]
[1.99999802 3.99999407 2.99999604]
[1.99999951 3.99999852 3.0000004 ]
[1.99999953 3.9999998  3.0000001 ]
[1.99999993 3.99999978 2.99999985]
[1.99999998 3.99999994 3.00000001]
[1.99999998 3.99999999 3.        ]
[2.         3.99999999 2.99999999]
[2. 4. 3.]
[2. 4. 3.]
[2. 4. 3.]
