In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from tensorflow.keras.datasets import imdb
(train_data, train_labels), (test_data, test_labels) = imdb.load_data(num_words=10000)

In [16]:
word_index = imdb.get_word_index()
rev_index = dict(
[(value, key) for (key, value) in word_index.items()])

In [3]:
dim = len(word_index)

In [4]:
dim

88584

In [30]:
def code(wire):
    return [word_index[i] for i in wire.split(" ")]
def decode(wire):
    return " ".join(rev_index.get(i-3,"?") for i in wire)
def vectorize(wires, dimensions=10000):
    result = np.zeros((len(wires), dimensions))
    for i,wire in enumerate(wires):
        result[i,wire] = 1
    return result

In [6]:
x_train = vectorize(train_data)
x_test = vectorize(test_data)

In [7]:
y_train = np.asarray(train_labels).astype('float32')
y_test = np.asarray(test_labels).astype('float32')

In [8]:
from tensorflow.keras import models
from tensorflow.keras import layers

In [9]:
model = models.Sequential()
model.add(layers.Dense(16, activation='relu', input_shape=(10000,)))
model.add(layers.Dense(16, activation='relu'))
model.add(layers.Dense(1, activation='sigmoid'))
model.compile(optimizer='rmsprop',
loss='binary_crossentropy',
metrics=['accuracy'])


In [10]:
model.fit(x_train, y_train, epochs=3, batch_size=512)

Train on 25000 samples
Epoch 1/3
25000/25000 [==============================] - 14s 573us/sample - loss: 0.4469 - accuracy: 0.8267
Epoch 2/3
25000/25000 [==============================] - 3s 108us/sample - loss: 0.2540 - accuracy: 0.9110
Epoch 3/3
25000/25000 [==============================] - 3s 115us/sample - loss: 0.2005 - accuracy: 0.9272


In [11]:
results = model.evaluate(x_test, y_test)

25000/25000 [==============================] - 23s 925us/sample - loss: 0.2811 - accuracy: 0.8892


In [12]:
results

[0.28105084961891175, 0.88916]

In [14]:
c = code("the film was good")

In [17]:
decode(c)

'the film was good'

In [18]:
v = vectorize(c)

In [19]:
v

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [20]:
model.predict(v)

array([[0.50930923],
       [0.5214468 ],
       [0.51939493],
       [0.51216567]], dtype=float32)

In [21]:
c = code("the cast and the characters were good overall and the storyline was great i would give a 5 star review")

In [22]:
v = vectorize(c)

In [23]:
model.predict(v)

array([[0.50930923],
       [0.53354406],
       [0.52083594],
       [0.50930923],
       [0.52050555],
       [0.5062628 ],
       [0.51216567],
       [0.57799673],
       [0.52083594],
       [0.50930923],
       [0.56634456],
       [0.51939493],
       [0.5306569 ],
       [0.48307306],
       [0.5152366 ],
       [0.56065625],
       [0.5322307 ],
       [0.5527536 ],
       [0.47425568],
       [0.49473628]], dtype=float32)

In [24]:
decode(c)

'the cast and the characters were good overall and the storyline was great i would give a 5 star review'

In [25]:
c = code("good great wonderful beautiful fantastic awesome")

In [26]:
v = vectorize(c)

In [27]:
model.predict(v)

array([[0.51216567],
       [0.5306569 ],
       [0.5744833 ],
       [0.51759416],
       [0.5505773 ],
       [0.49796435]], dtype=float32)

In [32]:
decode(test_data[0])

"? please give this one a miss br br ? ? and the rest of the cast rendered terrible performances the show is flat flat flat br br i don't know how michael madison could have allowed this one on his plate he almost seemed to know this wasn't going to work out and his performance was quite ? so all you madison fans give this a miss"

In [33]:
test_labels[0]

0

In [48]:
model.predict(x_test[0:3])

array([[0.21314114],
       [0.9985631 ],
       [0.9556926 ]], dtype=float32)

In [71]:
c = np.array([
    code("bad poor pathetic sad don't upset"),
    code("this film requires a lot of patience because it focuses on mood and character development the plot is very simple and many of the scenes take place on the same set in frances the sandy dennis character apartment but the film builds to a disturbing climax br br the characters create an atmosphere with sexual tension and psychological its very interesting that robert altman directed this considering the style and structure of his other films still the trademark altman audio style is evident here and there i think what really makes this film work is the brilliant performance by sandy dennis its definitely one of her darker characters but she plays it so perfectly and convincingly that it's scary michael burns does a good job as the mute young man regular altman player michael murphy has a small part the moody set fits the content of the story very well in short this movie is a powerful study of loneliness sexual and desperation be patient up the atmosphere and pay attention to the wonderfully written script br br i praise robert altman this is one of his many films that deals with unconventional fascinating subject matter this film is disturbing but it's sincere and it's sure to a strong emotional response from the viewer if you want to see an unusual film some might even say bizarre this is worth the time br br unfortunately it's very difficult to find in video stores you may have to buy it off the internet"),
])

In [72]:
v = vectorize(c)

In [73]:
model.predict(v)

array([[0.42733023],
       [0.80568975]], dtype=float32)

In [59]:
decode(test_data[1])

"? this film requires a lot of patience because it focuses on mood and character development the plot is very simple and many of the scenes take place on the same set in frances ? the sandy dennis character apartment but the film builds to a disturbing climax br br the characters create an atmosphere ? with sexual tension and psychological ? it's very interesting that robert altman directed this considering the style and structure of his other films still the trademark altman audio style is evident here and there i think what really makes this film work is the brilliant performance by sandy dennis it's definitely one of her darker characters but she plays it so perfectly and convincingly that it's scary michael burns does a good job as the mute young man regular altman player michael murphy has a small part the ? moody set fits the content of the story very well in short this movie is a powerful study of loneliness sexual ? and desperation be patient ? up the atmosphere and pay attenti