# More Numpy from O'Rielly Book

In [1]:
import numpy as np

In [2]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [9]:
np.ones(5,dtype=int)

array([1, 1, 1, 1, 1])

In [16]:
n = np.arange(10).reshape(5,2)

In [21]:
n.ndim

2

In [22]:
n

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [23]:
n.sum()

45

In [24]:
n.sum(axis=0)

array([20, 25])

In [26]:
n.sum(axis=1)

array([ 1,  5,  9, 13, 17])

In [27]:
n.sum(-1)

array([ 1,  5,  9, 13, 17])

In [30]:
n.sum((0,-1))

45

In [39]:
m = np.arange(30).reshape(5,2,3)
m.sum(2)

array([[ 3, 12],
       [21, 30],
       [39, 48],
       [57, 66],
       [75, 84]])

In [33]:
m

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29]]])

In [34]:
m.sum()

435

In [35]:
m.sum(0)

array([[60, 65, 70],
       [75, 80, 85]])

In [36]:
m.sum(1)

array([[ 3,  5,  7],
       [15, 17, 19],
       [27, 29, 31],
       [39, 41, 43],
       [51, 53, 55]])

In [38]:
m.sum(2) # Colapsing around the 3rd axis! ALHAMDOLILLAH!

array([[ 3, 12],
       [21, 30],
       [39, 48],
       [57, 66],
       [75, 84]])

In [ ]:
m.sum(3)