In [1]:
import numpy as np

In [3]:
ar = np.arange(20).reshape(5,4)

In [4]:
ar

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [9]:
bar = ar[0]

In [10]:
bar

array([0, 1, 2, 3])

In [11]:
bar[:] = 5

In [12]:
bar

array([5, 5, 5, 5])

In [13]:
ar

array([[ 5,  5,  5,  5],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [14]:
ar = np.arange(20).reshape(5,4)

In [15]:
ar

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [16]:
b = ar[[0]]

In [18]:
b[0] = 1

In [19]:
b

array([[1, 1, 1, 1]])

In [20]:
ar

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [21]:
b = ar[[1,2,3],[1,2,3]]

In [22]:
b

array([ 5, 10, 15])

In [23]:
b = ar[[1,2,3]][:,[1,2,3]]

In [24]:
b

array([[ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]])

In [25]:
 x = np.arange(24).reshape(4,2,3)

In [26]:
x

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]]])

In [37]:
x.sum((0,2))

array([120, 156])

In [41]:
np.allclose((np.array([1., 2., 3.]) / 10),(np.array([0.1, 0.2, 0.3])))

True