In [1]:
import numpy as np

In [2]:
l1 = [1, 2, 3, ]

In [3]:
ar = np.array(l1)

In [4]:
ar

array([1, 2, 3])

In [5]:
ar = ar.astype("str")

In [6]:
print(ar)

['1' '2' '3']


In [7]:
i = np.eye(5)

In [8]:
i

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [9]:
o = np.zeros(3)

In [10]:
o

array([0., 0., 0.])

In [11]:
np.random.random((5,5))

array([[0.50853731, 0.13006783, 0.81719454, 0.6138583 , 0.17163724],
       [0.46621694, 0.26264868, 0.51628636, 0.90559331, 0.37945352],
       [0.37790922, 0.78805932, 0.83284738, 0.71382093, 0.34741766],
       [0.4595167 , 0.54199502, 0.68619803, 0.81520057, 0.09969283],
       [0.05925173, 0.3134112 , 0.59721452, 0.46704958, 0.20826532]])

In [17]:
np.arange(22,12,-1)

array([22, 21, 20, 19, 18, 17, 16, 15, 14, 13])

In [18]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [20]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [28]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [34]:
np.linspace(1,50)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.])

In [35]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [36]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [40]:
np.eye(5,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [42]:
np.random.rand(5)

array([0.48770048, 0.66524874, 0.61032436, 0.39026324, 0.16291706])

In [62]:
np.random.randint(0,50,3)

array([11,  6, 45])

In [72]:
r = np.random.rand(3)

In [77]:
r.shape

(3,)

In [78]:
r.min()

0.1732546993060422

In [79]:
r.max()

0.8607601824843294

In [80]:
r.max

<function ndarray.max>

In [81]:
r

array([0.7406032 , 0.1732547 , 0.86076018])

In [84]:
r.argmin()

1

In [85]:
r.argmax()

2

In [86]:
r.reshape

<function ndarray.reshape>

In [91]:
np.array([1,2,3,4]).reshape(2,2)

array([[1, 2],
       [3, 4]])

In [94]:
r.dtype

dtype('float64')

In [108]:
np.ones(4,dtype="object")

array([1, 1, 1, 1], dtype=object)

In [98]:
print(r)

[0.7406032  0.1732547  0.86076018]


In [110]:
r.astype("str")

array(['0.7406031974543548', '0.1732546993060422', '0.8607601824843294'],
      dtype='<U32')

In [111]:
np.random.randn(2)

array([-0.97161778, -0.87163604])

In [117]:
np.random.rand(2,2)

array([[0.73152799, 0.68595233],
       [0.77387849, 0.70475096]])

In [118]:
np.ones(2)

array([1., 1.])

In [121]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [125]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [126]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [134]:
np.random.random(3)

array([0.81464183, 0.76618435, 0.97100125])

In [135]:
np.random.randn(50)

array([ 0.31515777,  1.14462374, -0.41993141,  0.18473735, -1.00386905,
       -0.98805108, -0.5819079 , -0.54631035, -1.0563791 , -0.86908023,
       -1.00403251,  1.04631233, -0.93579508,  1.13836022,  0.5456972 ,
       -1.63987712, -0.78189879,  0.26946593,  0.60972727,  1.7973238 ,
       -0.08819093,  0.03448767,  1.32676496, -0.70695505,  1.08586068,
       -0.64955535,  0.75963862,  1.53074851,  0.16476948, -0.8474043 ,
        0.31187684,  2.79755305, -0.14813512,  0.36707897,  0.89145312,
       -0.14954549, -0.51101217,  0.46788516, -0.15047345,  0.21893448,
       -0.33561395,  0.07743367, -1.60773627, -1.63367423, -0.76388552,
       -0.92456749, -0.29927479, -0.19199438, -1.31801576,  0.12043732])

# Indexing and Slicing

In [142]:
ar = np.arange(0,11)

In [143]:
ar[5]

5

In [144]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [145]:
ar[:5]

array([0, 1, 2, 3, 4])

In [146]:
ar[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [147]:
ar[5:]

array([ 5,  6,  7,  8,  9, 10])

In [148]:
ar[:6] = 99

In [149]:
ar

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [150]:
ar_copy = ar

In [151]:
ar_copy[0:3] = 33

In [152]:
ar

array([33, 33, 33, 99, 99, 99,  6,  7,  8,  9, 10])

In [153]:
ar_copy2 = ar[:]

In [154]:
ar_copy2

array([33, 33, 33, 99, 99, 99,  6,  7,  8,  9, 10])

In [155]:
ar_copy2[8:11] = 11

In [156]:
ar_copy2

array([33, 33, 33, 99, 99, 99,  6,  7, 11, 11, 11])

In [157]:
ar

array([33, 33, 33, 99, 99, 99,  6,  7, 11, 11, 11])

In [158]:
l1 = [1, 2, 3, 4, 5, ]

In [159]:
l2 = l1

In [160]:
l2[4] = "B"

In [161]:
l2

[1, 2, 3, 4, 'B']

In [162]:
l1

[1, 2, 3, 4, 'B']

In [168]:
l3 = l1[:] 

In [174]:
l3 = list(l1)

In [175]:
l3 = l1.copy()

In [176]:
l3

[1, 2, 3, 4, 'B']

In [177]:
l3[4] = "C"

In [178]:
l3

[1, 2, 3, 4, 'C']

In [179]:
l1

[1, 2, 3, 4, 'B']

In [181]:
l1[0:3] = ["1","2"]

In [182]:
l1

['1', '2', 4, 'B']

In [183]:
ar

array([33, 33, 33, 99, 99, 99,  6,  7, 11, 11, 11])

In [184]:
arc = ar[0]

In [185]:
arc

33

In [186]:
arc = "0"

In [187]:
ar

array([33, 33, 33, 99, 99, 99,  6,  7, 11, 11, 11])

In [189]:
arc = ar[0:2]

In [190]:
arc

array([33, 33])

In [191]:
arc[0] = 44

In [192]:
ar

array([44, 33, 33, 99, 99, 99,  6,  7, 11, 11, 11])

In [193]:
l = 5

In [209]:
ar2d = np.array([[x for x in range(10)] for y in range(10,20)])

In [207]:
ar2d

array([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
       [ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
       [ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
       [ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
       [ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
       [ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
       [ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
       [ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
       [ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
       [ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]])

In [233]:
ar2d = np.array([[x+(y*10) for x in range(1,11)] for y in range(5)]) #python mah=gic ALHAMDOLILLAH

In [234]:
ar2d

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [241]:
ar2d[4][9]

50

In [242]:
ar2d[4,9]

50

In [246]:
ar2d[:5,:10]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [247]:
ar2d[:2,1:]

array([[ 2,  3,  4,  5,  6,  7,  8,  9, 10],
       [12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [248]:
ar2d[3:,2:]

array([[33, 34, 35, 36, 37, 38, 39, 40],
       [43, 44, 45, 46, 47, 48, 49, 50]])

In [249]:
ar2d

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

# Comparison with NP Arrays

In [251]:
baray = ar2d > 25

In [252]:
ar2d[baray]

array([26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
       43, 44, 45, 46, 47, 48, 49, 50])

In [258]:
ar2d[ar2d == 25]

array([25, 25])

In [259]:
ar2d[2][5] = 25

In [275]:
i = np.eye(5,10)

In [277]:
import numpy as np

In [274]:
print(numpy.array([[x+(y*10) for x in range(1,11)] for y in range(5)])[numpy.eye(5,10).astype("bool")])

[ 1 12 23 34 45]


In [269]:
i

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]])

In [278]:
ar2d

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 25, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [ ]:
ar2d[np.ones((5,10)).astype("int")]