In [0]:
import numpy as np

In [0]:
r  = np.arange(1,10).reshape(3,3)

In [3]:
r

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
r[2,::]

array([7, 8, 9])

In [8]:
r[2,::].shape

(3,)

In [12]:
r[2:,:]

array([[7, 8, 9]])

In [15]:
r[2:,:].shape

(1, 3)

In [16]:
r

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
r[1,:2]

array([4, 5])

In [21]:
r[1:2,:2]

array([[4, 5]])

In [32]:
r.astype("str")

array([['1', '2', '3'],
       ['4', '5', '6'],
       ['7', '8', '9']], dtype='<U21')

In [24]:
print(r)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [34]:
r[0][0:2]

array([1, 2])

In [0]:
ar = np.arange(1,21).reshape(5,4)

In [36]:
ar

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [38]:
ar[2:4][1:3]

array([[13, 14, 15, 16]])

In [42]:
ar[0:2][0:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [43]:
ar[0:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [41]:
ar[0:2,0:2]

array([[1, 2],
       [5, 6]])